Repository TenPaws/Team_TenPaws, pull requests merged in 2024-12, with the labels that each got.

#2 [Mod] ChatGPT 추천 로직 개선
  backend/src/main/java/com/example/tenpaws/domain/recommendation/service/RecommendService.java
Labels: modify

#6 Design/매칭페이지퍼블리싱/#3
  frontend/src/components/Header.tsx
  frontend/src/pages/matching/DetailPage.tsx
  frontend/src/pages/matching/MatchingPage.tsx
  frontend/src/pages/my/MyPageShelter.tsx
  frontend/src/pages/my/MyPageUser.tsx
Labels: design

#8 선호동물 등록 페이지, 보호소 주소, 동물 상세보기 페이지 퍼블리싱
  frontend/src/components/Header.tsx
  frontend/src/components/HeaderLogin.tsx
  frontend/src/pages/CreateUser1.tsx
  frontend/src/pages/Signup.tsx
  frontend/src/pages/matching/DetailCorrect.tsx
  frontend/src/pages/matching/DetailReadPage.tsx
  frontend/src/pages/matching/MatchingPage.tsx
  frontend/src/pages/matching/PreferPage.tsx
  frontend/src/pages/my/MyPageUser.tsx
  frontend/src/pages/my/ShelterAddress.tsx
Labels: design

#16 Design/ai매칭페이지/#10
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/HeaderLogin.tsx
  frontend/src/pages/AIMatching.tsx
  frontend/src/pages/CreateUser1.tsx
  frontend/src/pages/matching/DetailCorrect.tsx
  frontend/src/pages/matching/DetailPage.tsx
  frontend/src/pages/matching/DetailReadPage.tsx
  frontend/src/pages/matching/MatchingPage.tsx
  frontend/src/pages/matching/PreferPage.tsx
  frontend/src/pages/my/AdoptionList.tsx
  frontend/src/pages/my/MyPageShelter.tsx
  frontend/src/pages/my/MyPageUser.tsx
  frontend/src/pages/my/ShelterAddress.tsx
Labels: design

#13 [Add] pet createdDate 추가, introduction 추가
  backend/src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  backend/src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  backend/src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  backend/src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: add

#15 [Feat] 회원의 신청상태 추가 및 변경 로직 추가
  backend/src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  backend/src/main/java/com/example/tenpaws/domain/user/dto/UserResponseDTO.java
  backend/src/main/java/com/example/tenpaws/domain/user/entity/User.java
  backend/src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: feat

#17 [Setting] 배포
  .github/workflows/deploy.yml
  backend/Dockerfile
  backend/appspec.yml
  backend/scripts/start-server.sh
  backend/src/main/java/com/example/tenpaws/global/advice/OAuth2SuccessHandler.java
  backend/src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  docker-compose.template.yml
  frontend/src/components/Chat.tsx
  frontend/src/components/FAQ.tsx
  frontend/src/components/FAQEdIt.tsx
  frontend/src/pages/guide/Announcement.tsx
  frontend/src/pages/guide/AnnouncementEdit.tsx
  frontend/src/pages/guide/Announcementpost.tsx
  frontend/src/pages/guide/Announcementpostcreate.tsx
  frontend/src/pages/guide/QAandApost.tsx
  frontend/src/pages/guide/QAandApostcreate.tsx
  frontend/src/pages/guide/QAndA.tsx
  frontend/src/pages/guide/QAndAEdit.tsx
  frontend/src/pages/matching/DetailCorrect.tsx
  frontend/src/pages/matching/DetailPage.tsx
  frontend/src/pages/matching/DetailReadPage.tsx
  frontend/src/pages/matching/MatchingPage.tsx
  frontend/src/pages/my/MyPageShelter.tsx
  frontend/src/pages/my/MyPageUser.tsx
  frontend/src/store/store.ts
  frontend/src/utils/axiosInstance.ts
Labels: setting

#24 [Fix] 입양 신청 동시성 문제 개선
  backend/settings.gradle
  backend/src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  backend/src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  backend/src/main/java/com/example/tenpaws/domain/pet/repository/PetRepository.java
  backend/src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  backend/src/main/java/com/example/tenpaws/global/util/TestDataScriptGenerator.java
  backend/src/test/java/com/example/tenpaws/PasswordEncoderTest.java
Labels: fix

#29 [Mod] : CI/CD 기본 브랜치 develop으로 변경
  .github/workflows/deploy.yml
Labels: modify

#30 fix : Docker 볼륨 경로를 SpringBoot 컨테이너 루트 디렉토리의 /uploads 로 수정
  docker-compose.template.yml
Labels: fix
